# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_cadastre_se.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import self as self
from PyQt5 import QtCore, QtGui, QtWidgets, uic
import sqlite3
import re



def checar_lineEdit():
    nome = ui.lineEdit_nome.text()
    email = ui.lineEdit_email.text()
    senha = ui.lineEdit_senha.text()
    con_senha = ui.lineEdit_con_senha.text()

    if nome and email and senha and con_senha != "":
        checar_email()

    else:
        ui.frame_erro.show()
        ui.texto_erro.setText('Possui Campos Vazios')

def checar_email():
    regex = '^[a-zA-Z0-9._-]+@[a-zA-Z0-9]+\.[a-zA-Z\.a-zA-Z]{1,6}$'
    email = ui.lineEdit_email.text()

    if (re.search(regex,email)):
        confirmar_senha()

    else:
        ui.frame_erro.show()
        ui.texto_erro.setText('Email Inválido')

def confirmar_senha():
    nome = ui.lineEdit_nome.text()
    email = ui.lineEdit_email.text()
    senha = ui.lineEdit_senha.text()
    con_senha = ui.lineEdit_con_senha.text()

    if senha != con_senha:
       ui.frame_erro.show()
       ui.texto_erro.setText('As senhas não Conferem')

    else:
        salvar_dados()

def salvar_dados ():
    nome = ui.lineEdit_nome.text()
    email = ui.lineEdit_email.text()
    senha = ui.lineEdit_con_senha.text()

    try:
        bd = sqlite3.connect('system.db')
        cursor = bd.cursor()
        cursor.execute("CREATE TABLE IF NOT EXISTS usuarios(id integer not null primary key AUTOINCREMENT,nome text not null,email text not null, senha text not null)")
        cursor.execute("INSERT INTO usuarios (nome, email, senha) VALUES ('%s' , '%s' , '%s')" %(nome, email, senha))
        bd.commit()
        bd.close()
        print('dados inseridos com sucesso')
    except sqlite3.Error as erro:
        print('erro')

def abre_tela_login():
    tela_login.show()

class Ui_bg_tela_cadastro(object):



    def setupUi(self, bg_tela_cadastro):
        bg_tela_cadastro.setObjectName("bg_tela_cadastro")
        bg_tela_cadastro.resize(645, 530)
        bg_tela_cadastro.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(bg_tela_cadastro)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_bg_geral = QtWidgets.QFrame(self.centralwidget)
        self.frame_bg_geral.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.frame_bg_geral.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_bg_geral.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bg_geral.setObjectName("frame_bg_geral")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_bg_geral)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_bg_informacoes = QtWidgets.QFrame(self.frame_bg_geral)
        self.frame_bg_informacoes.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_bg_informacoes.setMaximumSize(QtCore.QSize(500, 400))
        font = QtGui.QFont()
        font.setPointSize(2)
        self.frame_bg_informacoes.setFont(font)
        self.frame_bg_informacoes.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_bg_informacoes.setStyleSheet("background-color: rgba(0, 170, 255, 100);")
        self.frame_bg_informacoes.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bg_informacoes.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bg_informacoes.setObjectName("frame_bg_informacoes")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_bg_informacoes)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_erro = QtWidgets.QFrame(self.frame_bg_informacoes)
        self.frame_erro.setStyleSheet("background-color: rgb(229, 76, 115);")
        self.frame_erro.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_erro.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_erro.setObjectName("frame_erro")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_erro)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.texto_erro = QtWidgets.QLabel(self.frame_erro)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.texto_erro.setFont(font)
        self.texto_erro.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 8pt \"System\";")
        self.texto_erro.setAlignment(QtCore.Qt.AlignCenter)
        self.texto_erro.setObjectName("texto_erro")
        self.horizontalLayout_15.addWidget(self.texto_erro)
        self.pushButton = QtWidgets.QPushButton(self.frame_erro)
        self.pushButton.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon_fechar/fechar-o-simbolo-quadrado-arredondado-da-interface-com-uma-cruz (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_15.addWidget(self.pushButton)
        self.verticalLayout_2.addWidget(self.frame_erro)
        self.frame_cadastre_se = QtWidgets.QFrame(self.frame_bg_informacoes)
        self.frame_cadastre_se.setStyleSheet("")
        self.frame_cadastre_se.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_cadastre_se.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_cadastre_se.setObjectName("frame_cadastre_se")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_cadastre_se)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_cadastre_se = QtWidgets.QLabel(self.frame_cadastre_se)
        self.label_cadastre_se.setAutoFillBackground(False)
        self.label_cadastre_se.setStyleSheet("border:none;\n"
"font: 36pt \"MS Sans Serif\";\n"
"color: rgb(255, 255, 255);")
        self.label_cadastre_se.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cadastre_se.setObjectName("label_cadastre_se")
        self.horizontalLayout_2.addWidget(self.label_cadastre_se)
        self.verticalLayout_2.addWidget(self.frame_cadastre_se)
        self.frame_input_digite_nome = QtWidgets.QFrame(self.frame_bg_informacoes)
        self.frame_input_digite_nome.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_input_digite_nome.setStyleSheet("")
        self.frame_input_digite_nome.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_input_digite_nome.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_input_digite_nome.setObjectName("frame_input_digite_nome")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_input_digite_nome)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_7 = QtWidgets.QFrame(self.frame_input_digite_nome)
        self.frame_7.setMaximumSize(QtCore.QSize(300, 40))
        self.frame_7.setStyleSheet("border: 2px solid  rgb(255, 255, 255);\n"
"border-radius: 15px;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_4.setContentsMargins(6, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.icon_user = QtWidgets.QLabel(self.frame_7)
        self.icon_user.setMaximumSize(QtCore.QSize(40, 30))
        self.icon_user.setStyleSheet("border: none;")
        self.icon_user.setText("")
        self.icon_user.setPixmap(QtGui.QPixmap(":/icon_user/user.png"))
        self.icon_user.setScaledContents(True)
        self.icon_user.setObjectName("icon_user")
        self.horizontalLayout_4.addWidget(self.icon_user)
        self.lineEdit_nome = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_nome.setMaximumSize(QtCore.QSize(400, 300))
        self.lineEdit_nome.setStyleSheet("border: none;\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_nome.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_nome.setDragEnabled(False)
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.horizontalLayout_4.addWidget(self.lineEdit_nome)
        self.horizontalLayout_5.addWidget(self.frame_7)
        self.verticalLayout_2.addWidget(self.frame_input_digite_nome)
        self.frame_input_digite_email = QtWidgets.QFrame(self.frame_bg_informacoes)
        self.frame_input_digite_email.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_input_digite_email.setStyleSheet("")
        self.frame_input_digite_email.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_input_digite_email.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_input_digite_email.setObjectName("frame_input_digite_email")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_input_digite_email)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_8 = QtWidgets.QFrame(self.frame_input_digite_email)
        self.frame_8.setMaximumSize(QtCore.QSize(300, 40))
        self.frame_8.setStyleSheet("border: 2px solid  rgb(255, 255, 255);\n"
"border-radius: 15px;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_6.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.icon_email = QtWidgets.QLabel(self.frame_8)
        self.icon_email.setMaximumSize(QtCore.QSize(30, 30))
        self.icon_email.setStyleSheet("border: none;")
        self.icon_email.setText("")
        self.icon_email.setPixmap(QtGui.QPixmap(":/icon_email/email-marketing.png"))
        self.icon_email.setScaledContents(True)
        self.icon_email.setObjectName("icon_email")
        self.horizontalLayout_6.addWidget(self.icon_email)
        self.lineEdit_email = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_email.setMaximumSize(QtCore.QSize(400, 300))
        self.lineEdit_email.setStyleSheet("border: none;\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_email.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_email.setDragEnabled(False)
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.horizontalLayout_6.addWidget(self.lineEdit_email)
        self.horizontalLayout_7.addWidget(self.frame_8)
        self.verticalLayout_2.addWidget(self.frame_input_digite_email)
        self.frame_input_digitar_senha = QtWidgets.QFrame(self.frame_bg_informacoes)
        self.frame_input_digitar_senha.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_input_digitar_senha.setStyleSheet("")
        self.frame_input_digitar_senha.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_input_digitar_senha.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_input_digitar_senha.setObjectName("frame_input_digitar_senha")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_input_digitar_senha)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_9 = QtWidgets.QFrame(self.frame_input_digitar_senha)
        self.frame_9.setMaximumSize(QtCore.QSize(300, 40))
        self.frame_9.setStyleSheet("border: 2px solid  rgb(255, 255, 255);\n"
"border-radius: 15px;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_8.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.icon_senha = QtWidgets.QLabel(self.frame_9)
        self.icon_senha.setMaximumSize(QtCore.QSize(30, 30))
        self.icon_senha.setStyleSheet("border: none;")
        self.icon_senha.setText("")
        self.icon_senha.setPixmap(QtGui.QPixmap(":/icon_senha/cadeado.png"))
        self.icon_senha.setScaledContents(True)
        self.icon_senha.setObjectName("icon_senha")
        self.horizontalLayout_8.addWidget(self.icon_senha)
        self.lineEdit_senha = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_senha.setMaximumSize(QtCore.QSize(400, 300))
        self.lineEdit_senha.setStyleSheet("border: none;\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_senha.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_senha.setDragEnabled(False)
        self.lineEdit_senha.setObjectName("lineEdit_senha")
        self.horizontalLayout_8.addWidget(self.lineEdit_senha)
        self.horizontalLayout_9.addWidget(self.frame_9)
        self.verticalLayout_2.addWidget(self.frame_input_digitar_senha)
        self.frame_input_confirmar_senha = QtWidgets.QFrame(self.frame_bg_informacoes)
        self.frame_input_confirmar_senha.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_input_confirmar_senha.setStyleSheet("")
        self.frame_input_confirmar_senha.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_input_confirmar_senha.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_input_confirmar_senha.setObjectName("frame_input_confirmar_senha")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_input_confirmar_senha)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_10 = QtWidgets.QFrame(self.frame_input_confirmar_senha)
        self.frame_10.setMaximumSize(QtCore.QSize(300, 40))
        self.frame_10.setStyleSheet("border: 2px solid  rgb(255, 255, 255);\n"
"border-radius: 15px;")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_10.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.icon_con_senha = QtWidgets.QLabel(self.frame_10)
        self.icon_con_senha.setMaximumSize(QtCore.QSize(30, 30))
        self.icon_con_senha.setStyleSheet("border: none;")
        self.icon_con_senha.setText("")
        self.icon_con_senha.setPixmap(QtGui.QPixmap(":/icon_senha/cadeado.png"))
        self.icon_con_senha.setScaledContents(True)
        self.icon_con_senha.setObjectName("icon_con_senha")
        self.horizontalLayout_10.addWidget(self.icon_con_senha)
        self.lineEdit_con_senha = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_con_senha.setMaximumSize(QtCore.QSize(400, 300))
        self.lineEdit_con_senha.setStyleSheet("border: none;\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_con_senha.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_con_senha.setDragEnabled(False)
        self.lineEdit_con_senha.setObjectName("lineEdit_con_senha")
        self.horizontalLayout_10.addWidget(self.lineEdit_con_senha)
        self.horizontalLayout_11.addWidget(self.frame_10)
        self.verticalLayout_2.addWidget(self.frame_input_confirmar_senha)
        self.frame_ja_tenho_login = QtWidgets.QFrame(self.frame_bg_informacoes)
        self.frame_ja_tenho_login.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_ja_tenho_login.setStyleSheet("")
        self.frame_ja_tenho_login.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ja_tenho_login.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ja_tenho_login.setObjectName("frame_ja_tenho_login")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_ja_tenho_login)
        self.horizontalLayout_12.setContentsMargins(200, 0, 0, 19)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_ja_tem_login = QtWidgets.QPushButton(self.frame_ja_tenho_login)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_ja_tem_login.setFont(font)
        self.pushButton_ja_tem_login.setMouseTracking(False)
        self.pushButton_ja_tem_login.setStyleSheet("QPushButton {\n"
"\n"
"color: rgb(255, 255, 255);\n"
"border: none;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"color: rgb(229, 229, 229);\n"
"border: none;\n"
"\n"
"}")
        self.pushButton_ja_tem_login.setObjectName("pushButton_ja_tem_login")
        self.horizontalLayout_12.addWidget(self.pushButton_ja_tem_login)
        self.verticalLayout_2.addWidget(self.frame_ja_tenho_login)
        self.frame_btn_cadastre_se = QtWidgets.QFrame(self.frame_bg_informacoes)
        self.frame_btn_cadastre_se.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_btn_cadastre_se.setStyleSheet("")
        self.frame_btn_cadastre_se.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_btn_cadastre_se.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btn_cadastre_se.setObjectName("frame_btn_cadastre_se")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_btn_cadastre_se)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.pushButton_cadastre_se = QtWidgets.QPushButton(self.frame_btn_cadastre_se)
        self.pushButton_cadastre_se.setMaximumSize(QtCore.QSize(205, 55))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_cadastre_se.setFont(font)
        self.pushButton_cadastre_se.setStyleSheet("QPushButton{\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: ;\n"
"    background-color: rgb(1, 208, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"\n"
"}")
        self.pushButton_cadastre_se.setObjectName("pushButton_cadastre_se")
        self.horizontalLayout_14.addWidget(self.pushButton_cadastre_se)
        self.verticalLayout_2.addWidget(self.frame_btn_cadastre_se)
        self.horizontalLayout.addWidget(self.frame_bg_informacoes)
        self.horizontalLayout_13.addWidget(self.frame_bg_geral)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_13)
        bg_tela_cadastro.setCentralWidget(self.centralwidget)

        #FECHAR FRAME ERRO
        self.pushButton.clicked.connect(lambda: self.frame_erro.hide())
        #OCULTAR FRAME ERRO NA INICIALIZAÇAO
        self.frame_erro.hide()
        #BOTAO CADASTRE-SE
        ui.pushButton_cadastre_se.clicked.connect(checar_lineEdit)
        # BOTAO JA TEM LOGIN?
        ui.pushButton_ja_tem_login.clicked.connect(abre_tela_login)

        self.retranslateUi(bg_tela_cadastro)
        QtCore.QMetaObject.connectSlotsByName(bg_tela_cadastro)

    def retranslateUi(self, bg_tela_cadastro):
        _translate = QtCore.QCoreApplication.translate
        bg_tela_cadastro.setWindowTitle(_translate("bg_tela_cadastro", "MainWindow"))
        self.texto_erro.setText(_translate("bg_tela_cadastro", "TextLabel"))
        self.label_cadastre_se.setText(_translate("bg_tela_cadastro", "Cadastre-se"))
        self.lineEdit_nome.setPlaceholderText(_translate("bg_tela_cadastro", "Digite seu Nome"))
        self.lineEdit_email.setPlaceholderText(_translate("bg_tela_cadastro", "Digite seu Email"))
        self.lineEdit_senha.setPlaceholderText(_translate("bg_tela_cadastro", "Digite uma Senha"))
        self.lineEdit_con_senha.setPlaceholderText(_translate("bg_tela_cadastro", "Confirme sua Senha"))
        self.pushButton_ja_tem_login.setText(_translate("bg_tela_cadastro", "Já tem Login?"))
        self.pushButton_cadastre_se.setText(_translate("bg_tela_cadastro", "Cadastre-Se"))

import img

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    bg_tela_cadastro = QtWidgets.QMainWindow()
    ui = Ui_bg_tela_cadastro()
    ui.setupUi(bg_tela_cadastro)
    tela_login = uic.loadUi("login.ui")
    bg_tela_cadastro.show()
    sys.exit(app.exec_())
